--Crea una base de datos con el nombre Falabella viajes con las siguientes especificaciones:
CREATE DATABASE FALABELLAVIAJES
ON PRIMARY
(
	NAME='FALABELLAVIAJES_PRI',
	FILENAME='C:\AGENCIA_sql\falabella_viajes.MDF',
	SIZE=10MB,
	MAXSIZE=60,
	FILEGROWTH=5%
)
LOG ON
(
	NAME='FALABELLAVIAJES_LOG',
	FILENAME='C:\AGENCIA_sql\falabella_viajes.LDF',
	SIZE=9MB,
	MAXSIZE=20MB,
	FILEGROWTH=20%
)
GO

SELECT PAS.NOMBRES, SUM(PAG.MONTO)
FROM PASAJERO PAS JOIN PAGO PAG
ON PAS.IDPASAJERO = PAG.IDPASAJERO
JOIN RESERVA RES ON RES.IDRESERVA = PAG.IDRESERVA
JOIN PAIS PAI ON PAI.IDPAIS = PAS.IDPAIS
GROUP BY NOMBRES


SELECT *
FROM PASAJERO