--Crea una base de datos con el nombre Falabella viajes con las siguientes especificaciones:
CREATE DATABASE FALABELLAVIAJES
ON PRIMARY
(
	NAME='FALABELLAVIAJES_PRI',
	FILENAME='C:\AGENCIA_sql\falabella_viajes.MDF',
	SIZE=10MB,
	MAXSIZE=60,
	FILEGROWTH=5%
)
LOG ON
(
	NAME='FALABELLAVIAJES_LOG',
	FILENAME='C:\AGENCIA_sql\falabella_viajes.LDF',
	SIZE=9MB,
	MAXSIZE=20MB,
	FILEGROWTH=20%
)
GO

USE FALABELLAVIAJES
GO
SP_HELPFILE FALABELLAVIAJES_PRI

GO

USE FALABELLAVIAJES
GO
SP_HELPFILE FALABELLAVIAJES_LOG

GO
--Se debe mostrar los pasajeros que no han hecho reserva aún. Recuerde que debe utilizar
--JOINS.
SELECT *
FROM PASAJERO LEFT JOIN PAGO
ON PASAJERO.IDPASAJERO = PAGO.IDPASAJERO
LEFT JOIN RESERVA
ON RESERVA.IDRESERVA = PAGO.IDRESERVA
WHERE ISNULL(PAGO.MONTO,0) = 0
GO
--Se deberá crear un procedimiento almacenado que permita mostrar los países que aún no
--tienen pasajero registrado.
CREATE PROCEDURE MUESTRAPAISSINREGISTROS
AS
	SELECT PAIS.PAIS
	FROM PAIS LEFT JOIN PASAJERO
	ON PAIS.IDPAIS = PASAJERO.IDPAIS
	LEFT JOIN PAGO
	ON PAGO.IDPASAJERO = PASAJERO.IDPASAJERO
	GROUP BY PAIS
	HAVING ISNULL(COUNT(PASAJERO.IDPASAJERO),0)=0

EXEC MUESTRAPAISSINREGISTROS

--Deberá crear un procedimiento almacenado con parámetro de entrada, mostrar las
--reservas de un determinado pasajero para este caso deberá considerar como parámetro
--de entrada el nombre del pasajero, defina de manera adecuada la cabecera del listado e
--implemente un mensaje de error en el caso que el pasajero no exista.
GO
CREATE PROCEDURE MUESTRAREGISTROSPASAJERO(@NOMBRE VARCHAR(50))
AS
	SELECT DISTINCT(PASAJERO.NOMBRES), RESERVA.*
	FROM RESERVA JOIN PAGO
	ON RESERVA.IDRESERVA = PAGO.IDRESERVA
	JOIN PASAJERO 
	ON PAGO.IDPASAJERO = PASAJERO.IDPASAJERO
	WHERE PASAJERO.NOMBRES = @NOMBRE
GO
EXEC MUESTRAREGISTROSPASAJERO @NOMBRE = 'KARLA GALLEGOS SILVA'
GO

--Deberá crear un procedimiento almacenado en donde se debe mostrar el listado de los
--países y su total de pasajeros.
CREATE PROCEDURE MUESTRAPAISYCANTIDADPASAJEROS
AS
	SELECT PAIS.PAIS, COUNT(PASAJERO.IDPASAJERO) AS [CANTIDAD PASAJEROS]
	FROM PASAJERO JOIN PAIS
	ON PASAJERO.IDPAIS = PAIS.IDPAIS
	GROUP BY PAIS
GO

EXEC MUESTRAPAISYCANTIDADPASAJEROS

--Procedimiento almacenado que permita registrar a un nuevo pasajero para este caso
--deberá definir como parámetros de entrada todos los campos referentes al pasajero a
--excepción del IDPAIS; aquí deberá ingresar el nombre del país, en caso no existe emitir un
--mensaje de “País no registrado en la Base”. Finalmente, si el pasajero se registra
--correctamente emitir un mensaje de “Pasajero registrado con éxito”.

SELECT * FROM PAIS ORDER BY PAIS ASC
GO

CREATE FUNCTION VERIFICARPAIS(@PAIS VARCHAR(30))
RETURNS CHAR(4)
AS
BEGIN
	DECLARE @NOMBREPAIS CHAR(30) = 'ARGENTINA'
	SET @NOMBREPAIS =
	CASE @NOMBREPAIS
	WHEN 'ARGENTINA' THEN '0002' 
	WHEN 'BOLIVIA' THEN  '0009'
	WHEN 'BRASIL' THEN '0005'
	WHEN 'CHILE' THEN '0003'
	WHEN 'ECUADOR' THEN '0004'
	WHEN 'EEUU' THEN '0012'
	WHEN 'HONDURAS' THEN '0011'
	WHEN 'MEXICO' THEN '0010'
	WHEN 'PARAGUAY' THEN '0007'
	WHEN 'PERU' THEN '001'
	WHEN 'PUERTO RICO' THEN '0013'
	WHEN 'URUGUAY' THEN '0008'
	WHEN 'VENEZUELA' THEN '0006'
	ELSE 'País no registrado en la Base'
	END
	RETURN @NOMBREPAIS
END
GO

IF OBJECT_ID('REGISTROPASAJEROS') IS NOT NULL
BEGIN
	DROP PROCEDURE REGISTROPASAJEROS
END
GO

CREATE PROCEDURE REGISTROPASAJEROS
(@IDPASAJERO CHAR(5), @NOMBRE VARCHAR(50),@PAIS VARCHAR(30), @TELEFONO CHAR(15), @EMAIL VARCHAR(50))
AS
	IF EXISTS(SELECT PASAJERO.* FROM PASAJERO
			WHERE IDPASAJERO = @IDPASAJERO
			AND NOMBRES = @NOMBRE AND IDPAIS = DBO.VERIFICARPAIS(@PAIS)
			AND TELEFONO = @TELEFONO AND EMAIL = @EMAIL)
	BEGIN
		PRINT 'EL PASAJERO YA EXISTE'
	END
	ELSE
	BEGIN
		INSERT INTO PASAJERO VALUES (@IDPASAJERO,@NOMBRE,DBO.VERIFICARPAIS(@PAIS),@TELEFONO,@EMAIL)
		PRINT 'PASAJERO INGRESADO CON EXITO'
	END

EXEC REGISTROPASAJEROS @IDPASAJERO='1111',@NOMBRE='ANDREA ELIZABETH QUINTRILEF ALMUNA', @PAIS = 'CHILE', @TELEFONO = '930341603',@EMAIL='ANDREQUINTRILEF@GMAIL.COM'

--Procedimiento que permita registrar un nuevo País para lo cual deberá definir como
--parámetro de entrada al nombre del país, aquí se deberá comprobar que dicho país no
--haya sido registrado antes si fuera el caso emitir un mensaje de “País ya registrado”, el
--código de este país es autogenerado por lo tanto no se ingresara como parámetro.
--Finalmente, si todo es correcto emitir un mensaje de “País registrado correctamente”.
GO

IF OBJECT_ID('REGISTRARPAIS') IS NOT NULL
BEGIN
	DROP PROCEDURE REGISTRARPAIS
END
GO


CREATE PROCEDURE REGISTRARPAIS
(@ID CHAR(4),@PAIS VARCHAR(30))
AS
	IF EXISTS(SELECT * FROM PAIS WHERE PAIS.IDPAIS = @ID AND PAIS.PAIS = @PAIS)
	BEGIN
		PRINT 'PAIS YA REGISTRADO'
	END
	ELSE
	BEGIN
		INSERT INTO PAIS VALUES(@ID,@PAIS)
		PRINT 'PAIS REGISTRADO CORRECTAMENTE'
	END

EXEC REGISTRARPAIS @ID = '0014',@PAIS = 'COSTA RICA'

--quede en el 7 :D